CartOpt/Account/urls.py
from django.urls import path
from .views import *

app_name = 'Account'
urlpatterns = [
    path('login', LoginHandler.as_view(), name='login'),
    path('reg', RegisterHandler.as_view(), name='reg'),
    path('change', ChangeAccountInfo.as_view(), name='change'),
    path('logout', logout_handler, name='logout')
]

CartOpt/Cart/urls.py
from django.urls import path
from .views import *

var_name1='cart'
app_name = "Cart"

urlpatterns = [
    path(f'{var_name1}/view', ViewCart.as_view(),name='view'),
    path(f'{var_name1}/add/<int:id>', AddToCart.as_view(),name='add'),
    path(f'{var_name1}/remove/<int:id>', RemoveFromCart.as_view(),name='remove')
]

CartOpt/CartOpt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Cart/', include('Cart.urls')),
    path('', include('Product.urls')),
    path('Account/', include('Account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CartOpt/Product/urls.py
from django.urls import path
from .views import *

app_name='Product'
urlpatterns = [
    path('', ProdView.as_view(), name='view')
]

CartOpt/Product/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(
        max_length=250,
        null=False
    )
    price = models.PositiveBigIntegerField(default=0)

    
    def __str__(self):
        return f"{self.title} : {self.price}"

CartOpt/Product/views.py
from django.shortcuts import render
from django.views import View
from .models import Product
from django.contrib.auth.models import User
from Cart.models import TheCart

class ProdView(View):
    def get(self, request):
        products = Product.objects.all().order_by('title')
        return render(request, "Product/index.html", {
            'products': products
        })

CartOpt/Product/templates/Product/BASE.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cart lv1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Cart Starter</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Product:view' %}">Main</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'Cart:view' %}">View Cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'Account:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'Account:reg' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'Account:change' %}">Edit Prof</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'Account:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-current="page" href="#">Cart Wroth : {{ request.user.cart.total_price }}$</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
    {% block base %}
    {% endblock %}
    

CartOpt/Product/templates/Product/BASE_message.html
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags == "error" %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endif %}>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

CartOpt/Product/templates/Product/index.html
{% extends "Product/BASE.html" %}
{% load static %} 

{% block base %}
      <!-- Header -->  
       <br><br>
    <center>
        <h1>Products</h1>
    </center>

    <!-- Products List -->
    <div class="container container-mod">
      {% include "Product/BASE_message.html" %}
      <div class="table-holder">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Price</th>
                <th scope="col">AddToCart</th>
                <th scope="col">Count</th>
              </tr>
            </thead>
            <tbody>
              {% for prod in products %}  
                <tr>
                    <form method=post action="{% url 'Cart:add' prod.id %}">
                        {% csrf_token %}
                            <th scope="row">{{ forloop.counter }}</th>
                            <td name="prod-title">{{prod.title}}</td>
                            <td>{{prod.price}}$</td>
                            <td><button type="submit" class="btn btn-outline-success">Add To Cart</button></td>
                            <td><input name='count' placeholder='Enter The Count' type='number' class='form-control'></td>

                    </form>
                    <form method="post" action="{% url 'Cart:remove' prod.id %}">
                      {% csrf_token %}
                        {% for item in request.user.cart.items.all %}
                          {% if prod.id == item.item.id %}
                            <td><button class="btn btn-outline-danger">Remove From Cart</button></td>
                          {% endif %}
                        {% endfor %}
                    </form>

                </tr>
      </div>
            {% endfor %}
          </tbody>
        </div>
        </table>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        </body>
        </html>
{% endblock %}